### ISSUE TITLE
Adding njt (npm jump to)

### ISSUE THREAD

**Issue by kachkaev** [neibla/LaunchX#42]
Hi Neil 👋

I’m the author of [njt](https://njt.now.sh/) and I'm here from https://github.com/kachkaev/njt/issues/8.

WDYT of adding njt tool as a search engine in LaunchX? If we get it in, I can add LaunchX to njt’s [README](https://github.com/kachkaev/njt/blob/master/README.md#getting-njt), which can give your extension some extra traffic. Happy to submit a PR to you repo if you expect to find time to publish it later on 🙂

**Comment by kachkaev** [comment]
Ping @neibla 👋

**Comment by neibla** [comment]
Hi @kachkaev sorry for missing your original notification! 

Not a problem, will do a release following PR submission!

**Comment by kachkaev** [comment]
Thanks @neibla! See #43 🙌

**Comment by neibla** [comment]
@kachkaev awesome thanks for that. Released 0.0.2 with njt support!

**Comment by kachkaev** [comment]
Thanks for releasing a new version @neibla! I [added LaunchX to njt instructions](https://github.com/kachkaev/njt/commit/94517ca8b99e5d9e607a417b172a28d98c807821) – hope this will give you some extra users 😉
